import{a as w,S,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",$="50248807-4593db0d9cec2666d46b99efe",q=15;async function m(e,o=1){const s={key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q};try{return(await w.get(v,{params:s})).data}catch{iziToast.error({title:"Error",message:"Oops! Failed to load images. Please try again later.",position:"topRight"})}}const f=document.querySelector(".js-gallery"),M=new S(".js-gallery .gallery-link",{captionsData:"alt",captionDelay:250});function h(e){const o=e.map(({webformatURL:s,largeImageURL:a,tags:t,likes:r,views:n,comments:b,downloads:P})=>`<li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${t}" />
      </a>
      <div class="image-info">
        <p>Likes: <span>${r}</span></p>
        <p>Views: <span>${n}</span></p>
        <p>Comments: <span>${b}</span></p>
        <p>Downloads: <span>${P}</span></p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function R(){f.innerHTML=""}function y(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}function j(e){e.classList.remove("hidden")}function g(e){e.classList.add("hidden")}const E=document.querySelector(".js-form"),u=document.querySelector(".js-loader"),B=document.querySelector(".js-gallery"),c=document.querySelector("#load-more-button");let d="",i=1;const p=15;E.addEventListener("submit",O);c.addEventListener("click",x);async function O(e){if(e.preventDefault(),d=e.target.elements["search-text"].value.trim(),i=1,!d){l.warning({message:"Please enter a search term!",position:"topRight"});return}R(),g(c),y(u);try{const o=await m(d,i,p);if(o.hits.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(o.hits);const s=Math.ceil(o.totalHits/p);i<s?j(c):g(c)}catch(o){l.error({message:`Error: ${o.message}`,position:"topRight"})}finally{L(u),E.reset()}}async function x(){i+=1,y(u);try{const e=await m(d,i,p);h(e.hits);const o=Math.ceil(e.totalHits/p);i>=o&&(g(c),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),A()}catch(e){l.error({message:`Error: ${e.message}`,position:"topRight"})}finally{L(u)}}function A(){const{height:e}=B.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
