import{S as E,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const S="https://pixabay.com/api/",v="50248807-4593db0d9cec2666d46b99efe";async function f(e,o=1,a=15){const s=`${S}?key=${v}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`,t=await fetch(s);if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return await t.json()}const m=document.querySelector(".js-gallery"),P=new E(".js-gallery .gallery-link",{captionsData:"alt",captionDelay:250});function g(e){const o=e.map(({webformatURL:a,largeImageURL:s,tags:t,likes:r,views:i,comments:w,downloads:b})=>`<li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${t}" />
      </a>
      <div class="image-info">
        <p>Likes: <span>${r}</span></p>
        <p>Views: <span>${i}</span></p>
        <p>Comments: <span>${w}</span></p>
        <p>Downloads: <span>${b}</span></p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),P.refresh()}function q(){m.innerHTML=""}function h(e){e.classList.remove("hidden")}function y(e){e.classList.add("hidden")}function j(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}const $=document.querySelector(".js-form"),d=document.querySelector(".js-loader"),M=document.querySelector(".js-gallery"),u=document.querySelector("#load-more-button");let l="",n=1;const p=15;$.addEventListener("submit",R);u.addEventListener("click",B);async function R(e){if(e.preventDefault(),l=e.target.elements["search-text"].value.trim(),n=1,!l){c.warning({message:"Please enter a search term!",position:"topRight"});return}q(),L(u),h(d);try{const o=await f(l,n,p);if(o.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(o.hits),o.totalHits>n*p&&j(u)}catch(o){c.error({message:`Error: ${o.message}`,position:"topRight"})}finally{y(d),$.reset()}}async function B(){n+=1,h(d);try{const e=await f(l,n,p);g(e.hits);const o=Math.ceil(e.totalHits/p);n>=o&&(L(u),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),H()}catch(e){c.error({message:`Error: ${e.message}`,position:"topRight"})}finally{y(d)}}function H(){const{height:e}=M.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
