import{a as w,S,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",$="50248807-4593db0d9cec2666d46b99efe",q=15;async function m(e,o=1){const s={key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q};try{return(await w.get(v,{params:s})).data}catch{iziToast.error({title:"Error",message:"Oops! Failed to load images. Please try again later.",position:"topRight"})}}const f=document.querySelector(".js-gallery"),M=new S(".js-gallery .gallery-link",{captionsData:"alt",captionDelay:250});function h(e){const o=e.map(({webformatURL:s,largeImageURL:a,tags:t,likes:r,views:l,comments:b,downloads:P})=>`<li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${t}" />
      </a>
      <div class="image-info">
        <p>Likes: <span>${r}</span></p>
        <p>Views: <span>${l}</span></p>
        <p>Comments: <span>${b}</span></p>
        <p>Downloads: <span>${P}</span></p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function R(){f.innerHTML=""}function y(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}function j(e){e.classList.remove("hidden")}function d(e){e.classList.add("hidden")}const E=document.querySelector(".js-form"),p=document.querySelector(".js-loader"),B=document.querySelector(".js-gallery"),i=document.querySelector("#load-more-button");let u="",n=1;const g=15;E.addEventListener("submit",O);i.addEventListener("click",x);async function O(e){if(e.preventDefault(),u=e.target.elements["search-text"].value.trim(),n=1,!u){c.warning({message:"Please enter a search term!",position:"topRight"});return}R(),d(i),y(p);try{const o=await m(u,n,g);if(o.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d(i);return}h(o.hits);const s=Math.ceil(o.totalHits/g);n<s?j(i):d(i)}catch(o){c.error({message:`Error: ${o.message}`,position:"topRight"})}finally{L(p),E.reset()}}async function x(){n+=1,y(p);try{const e=await m(u,n,g);h(e.hits);const o=Math.ceil(e.totalHits/g);n>=o&&(d(i),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),A()}catch(e){c.error({message:`Error: ${e.message}`,position:"topRight"})}finally{L(p)}}function A(){const{height:e}=B.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
